### ISSUE TITLE
Missing method to retrieve end_session_endpoint or logout

### ISSUE THREAD

**Issue by jsimonrichard** [ramosbugs/openidconnect-rs#111]
It would be nice to be able to log out using this framework. OpenID Connect requires there to be an end_session_endpoint URL, but as far as I can tell this library is missing a method to call or get that URL.

Is this the same as the revocation URL in the Google example or is this something different? It's present on the JSON discovery document at `.well-known/openid-configuration`.

**Comment by ramosbugs** [comment]
Hi @jsimonrichard,

This crate doesn't currently support the [OpenID Connect RP-Initiated Logout 1.0](https://openid.net/specs/openid-connect-rpinitiated-1_0.html) specification, and this field is not part of any of the supported standards listed on the [README](https://github.com/ramosbugs/openidconnect-rs#standards).

I would be open to a contribution that adds complete support for this standard, which I think should include:
- The `end_session_endpoint` in the OIDC Discovery metadata. Since this field isn't part of the OIDC Core standard, I wouldn't add it to `ProviderMetadata`. Rather, let's leverage `ProviderMetadata`'s `A: AdditionalProviderMetadata` type argument. We can do something along the lines of the following:
```rust
#[non_exhaustive]
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct LogoutProviderMetadata<A>
where A: AdditionalProviderMetadata {
    // Optional even though it's required by the spec so that clients can use the
    // field to determine whether the OP supports RP-initiated logout.
    pub end_session_endpoint: Option<EndSessionUrl>,
    #[serde(bound = "A: AdditionalProviderMetadata", flatten)]
    pub additional_metadata: A,
}
impl<A> AdditionalProviderMetadata for LogoutProviderMetadata<A>
where A: AdditionalProviderMetadata {}

pub type ProviderMetadataWithLogout = ProviderMetadata<
    LogoutProviderMetadata<EmptyAdditionalProviderMetadata>,
    CoreAuthDisplay,
    CoreClientAuthMethod,
    CoreClaimName,
    CoreClaimType,
    CoreGrantType,
    CoreJweContentEncryptionAlgorithm,
    CoreJweKeyManagementAlgorithm,
    CoreJwsSigningAlgorithm,
    CoreJsonWebKeyType,
    CoreJsonWebKeyUse,
    CoreJsonWebKey,
    CoreResponseMode,
    CoreResponseType,
    CoreSubjectIdentifierType,
>;
```
This would allow client code to be written as follows:
```rust
let provider_metadata = ProviderMetadataWithLogout::discover(issuer_url, http_client)?;
let end_session_endpoint = provider_metadata.additional_metadata().end_session_endpoint;
```
- A `LogoutRequest` struct similar to `AuthorizationRequest` that implements a builder pattern for setting the optional logout URL fields described in the [spec](https://openid.net/specs/openid-connect-rpinitiated-1_0.html#RPLogout). Calling a `url()` method on it would return the completed `Url` (similar to `AuthorizationRequest::url()`). I think I would implement `From<EndSessionUrl> for LogoutRequest` for constructing a request from the end session endpoint URL.
- Test coverage

If this is too much work, the first part should be all you need to get access to the provider metadata field, and you can use it entirely from your code without needing to modify this crate. Hope that helps!

**Comment by jsimonrichard** [comment]
That makes more sense; thanks for the clarification on the spec.

I'll spend some more time on the PR today.
