### ISSUE TITLE
Support standard OIDC birthdate claim

### ISSUE THREAD

**Issue by alex-swift** [ramosbugs/openidconnect-rs#119]
OpenID Connect Core  defines the list of the standard claims https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims.  One of these claims is `birthdate`.
 
`StandardClaims` structure supports `birthday`, but does not support `birthdate`:
@see https://github.com/ramosbugs/openidconnect-rs/blob/1bc4a2f6c741f1c94716c5f4d897b0f3eaa06fbe/src/claims.rs#L107

Could you please add support for `birthdate` claim or rename `birthday` by `birthdate`?

**Comment by ramosbugs** [comment]
ah shoot this looks like a typo. nice catch!

to avoid introducing a breaking change in case anyone depends on `birthday`, I think we'll need to add `birthdate` (of existing type `EndUserBirthday`) rather than rename `birthday`. I'm not sure when I'll have time to do this, but I would be happy to merge a PR that does this (with test coverage that adds the field to existing tests).

**Comment by alex-swift** [comment]
@ramosbugs, please review https://github.com/ramosbugs/openidconnect-rs/pull/120

**Comment by alex-swift** [comment]
Thank you for quick response.

**Comment by ramosbugs** [comment]
This is now fixed in [3.3.0](https://crates.io/crates/openidconnect/3.3.0)
