### ISSUE TITLE
Support for JWT access_tokens?

### ISSUE THREAD

**Issue by upachler** [ramosbugs/openidconnect-rs#15]
Hello, 

I'm currently trying to use Keycloak (www.keycloak.org) as OP with openidconnect-rs. Keycloak uses JWT access_tokens, which I'd like to validate with the keys present in the library. However, I couldn't find a way to do so, nor could I find documentation to do that. 

Am I missing something? If not, is this feature planned?

Thanks,
Uwe

**Comment by ramosbugs** [comment]
as far as I understand the OIDC standards, access tokens are opaque values that are only meaningful at the application layer. unlike ID tokens, access tokens aren't specified to be JWTs, so I don't think it makes sense to add this sort of functionality to this crate. if there's a newer standardized OIDC extension that talks about JWT access tokens, I'll gladly consider it for inclusion in this crate. otherwise, these JWTs will need to be handled by the application.

as far as accessing the keys, this crate provides a [`ProviderMetadata::jwks`](https://docs.rs/openidconnect/1.0.0-alpha.13/openidconnect/struct.ProviderMetadata.html#method.jwks) method. [`JsonWebKey::verify_signature`](https://docs.rs/openidconnect/1.0.0-alpha.13/openidconnect/trait.JsonWebKey.html#tymethod.verify_signature) can then be used to verify an arbitrary JWS signature.
