### ISSUE TITLE
How do I get a google refresh token / set access_type HTTP query parameter to offline?

### ISSUE THREAD

**Issue by bes** [ramosbugs/openidconnect-rs#2]
Hi, thanks for a nice library 👀!

I can't really figure out how to get openidconnect-rs to attach the "access_type=offline" query parameter required for getting a Google refresh token.

Is there a way?

**Comment by bes** [comment]
Answer:

Use `.add_extra_param("access_type", "offline")` on `AuthorizationRequest`.

**Comment by bes** [comment]
The winning combination was

```
    let (authorize_url, csrf_state, nonce) = client
        .authorize_url(
            AuthenticationFlow::<CoreResponseType>::AuthorizationCode,
            CsrfToken::new_random,
            Nonce::new_random,
        )
        .add_extra_param("access_type", "offline")
        .add_extra_param("prompt", "consent")
        // add_scope, etc.
```

**Comment by ramosbugs** [comment]
glad you got it to work!

For `prompt`, there's actually native support in the library since it's part of the OIDC Core spec:
```
.add_prompt(CoreAuthPrompt::Consent)
```

`access_type` seems to be a Google-specific extension, so the solution you arrived at is the only option. I'm not sure why Google went with this instead of using the `offline_access` scope defined here: https://openid.net/specs/openid-connect-core-1_0.html#OfflineAccess. It's possible they implemented that before the spec was finalized.
