### ISSUE TITLE
Unable to parse `updated_at` timestamp from Auth0

### ISSUE THREAD

**Issue by phated** [ramosbugs/openidconnect-rs#23]
I'm working on integrating this library with Auth0 and ran into an issue where the format of their `updated_at` field fails to parse. Their format is `"2020-06-16T03:23:10.426Z"`.

I changed this type to `String` in the `claims.rs` and it parses successfully.

**Comment by ramosbugs** [comment]
looks like @Auth0 isn't following the [OIDC spec](https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims):
> Time the End-User's information was last updated. Its value is a **JSON number** representing the number of seconds from 1970-01-01T0:0:0Z as measured in UTC until the date/time.

somehow they're a [certified OIDC implementation](https://openid.net/developers/certified/) but haven't bothered to follow the spec here, making their product incompatible with strongly-typed clients that do adhere to the spec.

that said, I would accept a PR that makes the serde parser also accept ISO 8601 date/time strings behind a non-default feature flag. the `updated_at` method should continue to return `Option<DateTime<Utc>>` though.

**Comment by phated** [comment]
I tried looking into this and the macros leave me complete stumped on trying to PR what you are asking for ☹️

**Comment by ramosbugs** [comment]
it's probably easiest to add the logic here:
https://github.com/ramosbugs/openidconnect-rs/blob/82aa3c6cf6ab39934e2cc64d5648282176444c26/src/macros.rs#L428-L453

**Comment by ramosbugs** [comment]
basically instead of `$map.next_value::<Option<Seconds>>` we probably need to replace `Option<Seconds>` with `serde_json::Value` or some other enum that accepts both strings and JSON numbers, and then accepts/parses the string representation only if the feature flag is enabled

**Comment by 187sec** [comment]
> looks like @Auth0 isn't following the [OIDC spec](https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims):
> 
> > Time the End-User's information was last updated. Its value is a **JSON number** representing the number of seconds from 1970-01-01T0:0:0Z as measured in UTC until the date/time.
> 
> 
> 
> somehow they're a [certified OIDC implementation](https://openid.net/developers/certified/) but haven't bothered to follow the spec here, making their product incompatible with strongly-typed clients that do adhere to the spec.
> 
> 
> 
> that said, I would accept a PR that makes the serde parser also accept ISO 8601 date/time strings behind a non-default feature flag. the `updated_at` method should continue to return `Option<DateTime<Utc>>` though.

HEWS Entitlements except for before said project before said research you're well now expected to pay the taxes did you have intrude and all LLCs you were not text exempt and you cannot file bankruptcy the only LLC that's legal in lawful is charity maturity and I love to make more than $26 an hour top pay ! And show me and contractors of federal government federal government and any government trying to overthrow sit inheritance send monetary said anything due to non-knowledge none under the privacy act the security exchange that states that I can revert back for any merger or any before any murder in and all businesses with the federal government government and all set forth shell from here they stay on that she'll be the way it isAnd even says federal government it's over no more monetary= space Kenya and Or service must be within the appropriate distance from peach tree*************^>>=Sid shell From here fourth be shihtamdarrej in the In the mirror To all saidsubjects entitlementsjerradalenmathews@yahoo.com/>; ALL ID
