### ISSUE TITLE
Token endpoint response parsing failure cause is not exposed to the caller

### ISSUE THREAD

**Issue by ximon18** [ramosbugs/openidconnect-rs#34]
With version 1.0.1 of the openid-connect Rust crate, when the response from the OpenID Connect token endpoint violates the OpenID Connect Core 1.0 specification, e.g. the "acr" ID Token claim value is not a string but is a structure, the "acr" parsing code returns an error describing the problem. However, by the the time the error is propagated back up to the caller the cause has been lost and all that remains is the unhelpful error message "Failed to parse server response".

Working out what was wrong required debugging the serde JSON deserializer call stack which is quite painful and not possible on a deployed system. Instead I had to depend on capturing the provider response in logs and using that to reproduce the issue in a test environment. This is not something you want to spend lots of time doing just to find out the issue with the data received from the OpenID Connect provider. Propagating the actual error back to the caller would be a huge improvement.

**Comment by ramosbugs** [comment]
assuming this refers to `RequestTokenError::Parse`, the underlying `serde_json::error::Error` is part of the enum variant returned to the caller.

in the 1.x release, that error is also chained using the `failure::Fail`'s trait's `#[cause]` annotation. in the 2.x release, it uses `thiserror::Error`'s `#[source]` annotation. I don't think `failure` or `thiserror` traverse the cause chain automatically in their `Display` or `Debug` implementations, so I recommend that your code iterate over the causes as part of its error handling. both crates provide an interface for doing that.

error chaining is still a rough edge in the Rust ecosystem at the moment (e.g., https://github.com/rust-lang/rust/issues/58520). something I've seen work well in a complex production system is liberal use of `#[source]`/`#[cause]` combined with a centralized error reporting function that walks over the causes and prints nicely formatted stack traces. I haven't found any public crates that do the formatting, but that would be a useful addition to the ecosystem.

**Comment by ximon18** [comment]
Thanks! I didn't consider that there might be more information than was being rendered. I will investigate traversing the error chain myself.

**Comment by ximon18** [comment]
Also thanks for the great contextual and best practice information that you gave in your response!

**Comment by ximon18** [comment]
My first attempt to improve the reported error has got me this far:

```
OpenID Connect: code exchange failed: Failed to parse server response: Failed to parse payload JSON: Error("invalid type: map, expected a string", line: 1, column: 226) at line 6 column 21 [response="{\n                        \"access_token\":\"*****\",\n                        \"token_type\":\"bearer\",\n                        \"expires_in\":299,\n                        \"id_token\":\"eyJra...<snip>...hhQ\"\n                    }"]
```

This is an improvement, but the real issue is inside the encoded `id_token` field and the partial deserialization of the `id_token` are not included in the error report, so the field that is a map rather than a string, the "acr" field, is not visible in the error message at all.

The code I have to make this error message looks like this:

```rust
let token_response: FlexibleTokenResponse = self.client
    .exchange_code(AuthorizationCode::new(code.to_string()))
    .request(logging_http_client!())
    .map_err(|e| {
        let msg = match e {
            RequestTokenError::ServerResponse(provider_err) => {
                format!("Server returned error response: {:?}", provider_err)
            },
            RequestTokenError::Request(req) => {
                format!("Request failed: {:?}", req)
            },
            RequestTokenError::Parse(parse_err, res) => {
                let body = match std::str::from_utf8(&res) {
                    Ok(text) => text.to_string(),
                    Err(_) => format!("{:?}", &res),
                };
                format!("Failed to parse server response: {} [response={:?}]",
                    parse_err, body)
            },
            RequestTokenError::Other(msg) => {
                msg
            },
        };
        MyErrorType::Custom(format!(
            "OpenID Connect: code exchange failed: {}", msg))
    })?;
```

Could I be so cheeky as to ask do you have any suggestions on how I can improve this?

Thanks,

Ximon

**Comment by ramosbugs** [comment]
the error implements `failure::Fail` in 1.x, so I'd call [`iter_chain`](https://docs.rs/failure/0.1.8/failure/trait.Fail.html#method.iter_chain) on it, then for each entry returned by the iterator, I usually print both the error [`name`](https://docs.rs/failure/0.1.8/failure/trait.Fail.html#method.name) as well as its `Display` output. you can optionally call  [`backtrace`](https://docs.rs/failure/0.1.8/failure/trait.Fail.html#method.backtrace) and print that too, although the default backtrace formatting in Rust is pretty unreadable.

**Comment by ramosbugs** [comment]
in other words, I'd operate at the trait level and not dig into specific enum variants unless you need to handle different causes differently (e.g., some causes might trigger retries but not others)

**Comment by ximon18** [comment]
Ah, thanks for that!

**Comment by ramosbugs** [comment]
I looked into this code path a bit more, and you're right that the crate reports the JSON deserialization error on the JWT payload without including the contents of that payload:
https://github.com/ramosbugs/openidconnect-rs/blob/f0031cfa0493ce80f62e056775e5412abe513b47/src/jwt.rs#L142-L145

the error gets bubbled up here:
https://github.com/ramosbugs/openidconnect-rs/blob/f0031cfa0493ce80f62e056775e5412abe513b47/src/jwt.rs#L403

unfortunately, the error handling options inside of a serde `Deserializer` are somewhat limited since the errors have to be converted to the generic `D::Error` associated type. in practical terms, this means having to stringify those errors using `D::Error::custom`. if we added the full JWT payload contents to that error string, it would probably result in an error that's too verbose for some contexts. that's probably why I originally put the raw response bytes into `RequestTokenError::Parse`. it does add an additional debugging step: manually extracting the JWT from the payload and then decoding it manually (or using a tool like https://www.jsonwebtoken.io/).

the biggest downside I see here is that if you follow my advice above about iterating generically over the error chain, the output won't have the raw payload response, and you won't be able to see that `acr` was the culprit. that seems like an issue worth fixing!

two ideas come to mind, though I welcome other suggestions:
1. a compile-time feature flag that tells the crate to include the full string in the error message when something fails to deserialize
2. leveraging `line` and `column` from [`serde_json::Error`](https://docs.serde.rs/serde_json/struct.Error.html) to intelligently extract the failed snippet from the payload and include it in the error message. this would be done when calling `DE::custom` above.

**Comment by ramosbugs** [comment]
I realized that the [serde_path_to_error](https://crates.io/search?q=serde_path_to_error) crate basically solves this use case, so I'm replacing `serde_json::Error` with `serde_path_to_error::Error<serde_json::Error>` as the last breaking change with the new beta releases

**Comment by ximon18** [comment]
Ah, interesting.
