### ISSUE TITLE
Validation error in issuer URI for a specific Discover

### ISSUE THREAD

**Issue by Armiixteryx** [ramosbugs/openidconnect-rs#38]
Hello.

Currently I am using this crate to perform authentication into Finastra FusionFabric, using an [example implementation](https://github.com/fusionfabric/ffdc-sample-nodejs/tree/master/ffdc-client-credentials) they provide in nodejs as reference.

The problem is here:

When discovering their OpenID configuration, I am getting the following error:

```
unexpected issuer URI `https://api.fusionfabric.cloud/login/v1` (expected `https://api.fusionfabric.cloud/login/v1/sandbox/
```

The discover url is the following: https://api.fusionfabric.cloud/login/v1/sandbox/.well-known/openid-configuration
and the raw response is here:

```json
{
  "issuer": "https://api.fusionfabric.cloud/login/v1",
  "authorization_endpoint": "https://api.fusionfabric.cloud/login/v1/sandbox/oidc/authorize",
  "token_endpoint": "https://api.fusionfabric.cloud/login/v1/sandbox/oidc/token",
  "userinfo_endpoint": "https://api.fusionfabric.cloud/login/v1/oidc/userinfo",
  "jwks_uri": "https://api.fusionfabric.cloud/login/v1/oidc/jwks.json",
  "grant_types_supported": [
    "authorization_code",
    "refresh_token",
    "client_credentials"
  ],
  "response_types_supported": [
    "code",
    "none",
    "id_token",
    "token",
    "id_token token",
    "code id_token",
    "code token",
    "code id_token token"
  ],
  "subject_types_supported": ["public", "pairwise"],
  "id_token_signing_alg_values_supported": ["RS256"],
  "userinfo_signing_alg_values_supported": ["RS256"],
  "request_object_signing_alg_values_supported": ["RS256"],
  "response_modes_supported": ["query", "fragment", "form_post"],
  "token_endpoint_auth_methods_supported": [
    "client_secret_post",
    "client_secret_basic",
    "private_key_jwt"
  ],
  "token_endpoint_auth_signing_alg_values_supported": ["RS256"],
  "claims_supported": ["sub", "auth_time", "iss", "tenant", "username"],
  "claim_types_supported": ["normal"],
  "claims_parameter_supported": false,
  "scopes_supported": ["openid"],
  "request_parameter_supported": true,
  "request_uri_parameter_supported": true,
  "code_challenge_methods_supported": ["plain", "S256"],
  "tls_client_certificate_bound_access_tokens": true
}
```

So this crate expects `issuer` value to be equal to the discover url, leading to the next question:

Can I say the Finastra implementation is not standard-compliant or it could be something worth to fix in this crate? (since the lib used in their npm example, `openid-client`, works good)...

Thank you for your help :)

**Comment by ramosbugs** [comment]
From my reading of the OpenID Connect Discovery [spec](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig), Finastra isn't following the standard (emphasis mine):
> OpenID Providers supporting Discovery MUST make a JSON document available at the path formed by **concatenating the string `/.well-known/openid-configuration` to the Issuer**.

Since the issuer returned in the metadata is `https://api.fusionfabric.cloud/login/v1`, this would mean that its discovery URL must be `https://api.fusionfabric.cloud/login/v1/.well-known/openid-configuration`. The issuer URL has some security implications since it has to match the `iss` claim during ID token verification. This crate tries to be defensive and reject inconsistent metadata that could lead to security issues.

In this case, it looks like Finastra is using the same `issuer` and `jwks_uri` values across its sandbox and production environments. This means that the two environments can trivially spoof each other's ID tokens, which could be a security vulnerability depending on whether consumers of the ID token need to differentiate between the two environments. From my experience working with other sandbox environments, this is likely a huge red flag, so I'd encourage you to report it to them.

We could add a flag to ignore the inconsistent issuer in this crate, but it's probably not worth doing that since it often indicates a problem with the OIDC provider, as illustrated above.

**Comment by maurerdietmar** [comment]
Here is another provider with the same problem:

https://cas.ucdavis.edu/cas/oidc/.well-known/openid-configuration

Any idea how to handle that?

**Comment by ramosbugs** [comment]
hmm... a slightly hacky solution that should work around this provider misconfiguration would be to provide a custom HTTP client wrapper function to [`ProviderMetadata::discover`](https://docs.rs/openidconnect/2.1.0/openidconnect/struct.ProviderMetadata.html#method.discover) (or `discover_async`) that replaces `https://cas.ucdavis.edu/.well-known/openid-configuration` in the requested [`url`](https://docs.rs/openidconnect/2.1.0/openidconnect/struct.HttpRequest.html#structfield.url) with `https://cas.ucdavis.edu/cas/oidc/.well-known/openid-configuration`. then, I think everything should validate with the issuer set to `https://cas.ucdavis.edu`. does that work?

**Comment by OmenWild** [comment]
> Here is another provider with the same problem:
> 
> https://cas.ucdavis.edu/cas/oidc/.well-known/openid-configuration

I contacted the service owner, and they are changing the service to meet the spec. I tested on the dev instance and it works great, so problem solved.

**Comment by ramosbugs** [comment]
Going to go ahead and close this issue since there hasn't been activity in almost a year, and the underlying issue is a misconfigured OIDC provider rather than an issue with the client.

**Comment by benoit9126** [comment]
It seems that I have this problem with the following provider https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration. In the retrieved JSON, the issuer URL is `https://login.microsoftonline.com/{tenantid}/v2.0` which doesn't match. Maybe @OmenWild has some contact here too 😅.
