### ISSUE TITLE
Implement `FromStr` for `IdToken`

### ISSUE THREAD

**Issue by Erik1000** [ramosbugs/openidconnect-rs#57]
We want to accept an [`IdToken`](https://docs.rs/openidconnect/2.1.2/openidconnect/struct.IdToken.html) from our clients (e.g. a cli that interacts with our REST API). For that, they should send their id token via a header (e.g. `Authorization` header with `Bearer` type). However, I've searched in the documentation and source code and can't find a way to get an `IdToken` from a String. The IdToken would be provided in the usual JWT Format (base64 encoded `header.claims.signature`). Am I missing something? If so, could you provide an example?

**Comment by Erik1000** [comment]
Okay, so I've looked through your code and saw that `JsonWebToken` (which is not accessible and hidden) manual implements `serde::Deserialize` which decodes the base64 string and parses the token (https://github.com/ramosbugs/openidconnect-rs/blob/main/src/jwt.rs#L328-L434). I see why you did this and it's probably useful but I'd suggest to also just implement [`FromStr`](https://doc.rust-lang.org/std/str/trait.FromStr.html) since most of the time, you get the `IdToken` as a regular string in a header for example.

**Comment by ramosbugs** [comment]
this seems like a reasonable use case, and it would simplify some of the tests as well since it wouldn't require first wrapping the ID token in quotes or an explicit `serde_json::Value::String`:
https://github.com/ramosbugs/openidconnect-rs/blob/69553597842f6630ed36d7d6b27a0286fcca020d/src/id_token.rs#L442-L447

We haven't needed this so far since most of the time the ID token is parsed as part of the OIDC provider's token response, but passing around just the ID token also makes sense in some cases.

I'd be happy to accept a PR that adds a `FromStr` impl for `IdToken`.

**Comment by Erik1000** [comment]
Well, that's a pretty small PR. I'll do. I will probably just call the `Deserialize` implementation to to avoid code duplication.
