### ISSUE TITLE
JWKs not serialized

### ISSUE THREAD

**Issue by andrewhickman** [ramosbugs/openidconnect-rs#67]
Hi, I notice currently the JWKs field of `ProviderMetadata` is never serialized. Is there a reason for that?

https://github.com/ramosbugs/openidconnect-rs/blob/d5cf0ae0c80893f060157225b77284710d481291/src/discovery.rs#L68-L69

I was hoping to serialize `ProviderMetadata` and cache it, but I wondered if there's some reason to not store the keys

**Comment by ramosbugs** [comment]
Hi @andrewhickman,

The serialized form of `ProviderMetadata` adheres to the [OpenID Connect spec](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata), which has a `jwks_uri` field but not the key contents. This makes the serialized form usable to implement an OIDC provider, since the types in this crate are intended to work for both provider and relying party implementations.

The in-memory representation of `ProviderMetadata` combines both the metadata and keys into a single struct for convenience when implementing a relying party (client). You should be able to serialize and cache the JsonWebKeySet separately, though.

Hope that helps!

**Comment by andrewhickman** [comment]
Makes sense, thanks!
