### ISSUE TITLE
Unknown grant type `urn:ietf:params:oauth:grant-type:device_code`

### ISSUE THREAD

**Issue by dfaust** [ramosbugs/openidconnect-rs#7]
Google seems to send a new kind of grant type in its discovery document causing `CoreProviderMetadata::discover` to fail.
The error stems from serde being unable to parse the new enum variant. Deserialization fails with the error:

```
Parse(Error("unknown variant `urn:ietf:params:oauth:grant-type:device_code`, expected one of `authorization_code`, `client_credentials`, `implicit`, `urn:ietf:params:oauth:grant-type:jwt-bearer`, `password`, `refresh_token`", line: 55, column: 48))
```

I suppressed the error by adding an additional variant to the `CoreGrantType` enum that catches all unknown grant types but I don't know enough about oauth2 or openidconnect to know if this is a good idea:

```rust
#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum CoreGrantType {
    // ...
    #[serde(other)]
    Unknown,
}
```

**Comment by ramosbugs** [comment]
Interesting, thanks for filing this issue!

My original thinking was for `openidconnect::core` to contain just the enum variants that are defined in the base OIDC specs (Core + Discovery, mainly). The reason the crate uses so many type parameters (e.g., for `Client`) is so that users of the crate can extend these definitions with their own types based on the OIDC providers they need to interoperate with, all while maintaining strong static typing.

However, it seems like this crate should support OIDC providers like Google out of the box, without requiring any special customization. In light of this issue, I think it would make sense to add a catch-all enum variant to many of the enums in `openidconnect::core`, but I think those enum variants should capture the value rather than drop it (i.e., `Unknown(String)` vs `Unknown` as a unit variant). This will unfortunately require a custom deserializer/serializer I think, since `serde(other)` only supports unit variants. I've run into this issue enough times though that I may submit a PR for `serde_derive` to support non-unit variants for `serde(other)`. I'll try to get around to adding the catch-all enum variants to `openidconnect::core` soon.

**Comment by ramosbugs** [comment]
It looks like https://github.com/serde-rs/serde/issues/912 is the relevant serde issue. I'll use one of the workaround for now

**Comment by dfaust** [comment]
It works perfect now. Thank you for the quick fix!

**Comment by metmeylmz** [comment]
> Google seems to send a new kind of grant type in its discovery document causing `CoreProviderMetadata::discover` to fail. The error stems from serde being unable to parse the new enum variant. Deserialization fails with the error:
> 
> ```
> Parse(Error("unknown variant `urn:ietf:params:oauth:grant-type:device_code`, expected one of `authorization_code`, `client_credentials`, `implicit`, `urn:ietf:params:oauth:grant-type:jwt-bearer`, `password`, `refresh_token`", line: 55, column: 48))
> ```
> 
> I suppressed the error by adding an additional variant to the `CoreGrantType` enum that catches all unknown grant types but I don't know enough about oauth2 or openidconnect to know if this is a good idea:
> 
> ```rust
> #[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
> #[serde(rename_all = "snake_case")]
> pub enum CoreGrantType {
>     // ...
>     #[serde(other)]
>     Unknown,
> }
> ```
