### ISSUE TITLE
Example usage from backend web server

### ISSUE THREAD

**Issue by stevepryde** [ramosbugs/openidconnect-rs#95]
Hoping someone can help me. All of the docs and examples seem to assume a stateful app, where you have the luxury of fetching the auth url and then waiting around for the code from the browser redirect.

However I'm trying to implement this with a traditional SPA with a frontend in the browser and backend on a server (REST API).

Here's my approach:
1. Frontend calls /get-auth-url on the backend, providing an email address
2. Backend does the following:
    - generate `pkce_challenge` / `pkce_verifier` as per example docs
    - get the `auth_url`, `csrf_token` and `nonce` via openidconnect as per example docs
    - store the `pkce_verifier`, `csrf_token` and `nonce` to a database record keyed by a new unique `session_id`
    - return the `auth_url` and `session_id` to the frontend 
3. Frontend stores `session_id` to local storage, then redirects to `auth_url`
4. Afterwards, frontend gets redirected to the `redirect_url`, which is /login/callback on the frontend (i.e. browser route, not backend)
5. Frontend calls /verify-auth on the backend, providing the `code` and `state` from the redirect url, and `session_id` from local storage
6. Backend can now do the following:
    - load the previously stored session record from the db by looking up the `session_id`
    - verify the `state` from the request against the `csrf_token` from the stored session record
    - get token response from openidconnect using the `code` from the request along with `pkce_verifier` (from the stored session record), as per example docs
    - get id token, also verifying with `nonce` (from stored session record), as per example docs
    - verify access token hash as per example docs
    - get `email` from claims and verify against the original email from the first request (step 1 above)

The session record is deleted from the db on successful auth (or invalidated after some timeout), and the session_id is also deleted from the browser's local storage in the redirect step.

Hoping someone can confirm this flow or point out anything I've missed.

Something that specifically puzzles me is this comment above `PkceCodeVerifier` in the oauth2 rust crate:
```rust
// This type intentionally does not implement Clone in order to make it difficult to reuse PKCE
// challenges across multiple requests.
```
This seems confusing since by definition there are two requests to the backend, one before and one after the browser redirect. Surely one needs to store the verifier value somewhere when using this in any stateless system (like a REST API)?

**Comment by stevepryde** [comment]
I saw something that mentioned PKCE is mainly for mobile apps, which makes sense since most docs / examples assume that you can generate the PKCE in before the auth redirect and still have access to it after the redirect. This isn't the case for a web backend server.

But if I'm not using PKCE, how do I know that the user who posts a request to my API after the callback is the same user who started the flow?

**Comment by ramosbugs** [comment]
Hey @stevepryde,

PKCE is designed for situations in which the OAuth2 client can't maintain a client secret (i.e., because it's a frontend-only or mobile application with no backend). Since your application ("relying party" in OIDC terminology) has a backend that's capable of storing a client secret ("confidential client" in OAuth2 terminology) to authenticate server-to-server communication between it and the OIDC provider, PKCE isn't really needed.

> Something that specifically puzzles me is this comment above `PkceCodeVerifier` in the oauth2 rust crate:
> 
> ```rust
> // This type intentionally does not implement Clone in order to make it difficult to reuse PKCE
> // challenges across multiple requests.
> ```
> 
> This seems confusing since by definition there are two requests to the backend, one before and one after the browser redirect. Surely one needs to store the verifier value somewhere when using this in any stateless system (like a REST API)?

I believe this comment is referring to the case where this crate is used in the context of an OIDC provider, rather than by a relying party (client). *Providers* should call `PkceCodeChallenge::new_random_sha256()` for each new authorization request, rather than providing the same challenge/verifier to multiple clients, which is a security issue that the lack of `Clone` is trying to help prevent. `PkceCodeVerifier` still implements `Serialize` and `Deserialize` though in case it needs to be stored by *clients* using this crate. The OIDC provider should only need to store the challenge, however, which is sufficient for verifying the verifier provided in the later client request.

From a brief review, I think the steps you outlined should work, though I haven't thought through every possible attacker interaction. I would be sure that the `session_id` has sufficient entropy that it can't be guessed by an attacker, since it's serving a similar purpose as the `csrf_token` in preventing session fixation attacks.

**Comment by stevepryde** [comment]
Thanks. That's super helpful. I think I've managed to put the pieces together.

Thanks for the crate btw.
